### ISSUE TITLE
Refactor RealmService

### ISSUE THREAD

**Issue by Karambirov** [Karambirov/GitHubSearch#45]
- [x] Method `create(_:completion:)` won't be used. So it needs to be deleted.
- [x] Method `fetch(_:predicate:sorted:completion:)` should't be generic.

**Comment by 5SMNOONMS5** [comment]
Hi, I am thinking maybe you cam just use [EasyRealm](https://github.com/PoissonBallon/EasyRealm)?

**Comment by Karambirov** [comment]
> Hi, I am thinking maybe you cam just use [EasyRealm](https://github.com/PoissonBallon/EasyRealm)?

1. The main idea is to use services, so we can isolate third-party frameworks from the rest of the app.
If we use EasyRealm, we must import it everywhere. So if you can isolate it in some kind of service, maybe we can use it.

2. Why do we need it at all? =) Can you show me a chunk of code from the app where you would use it and how?

**Comment by 5SMNOONMS5** [comment]
1. Haha, I think the main purpose for **EasyRealm** and **RealmService** are equal, so maybe only need one existence. so my idea is bad and conflict to this issue. 
2. You are right, we don't need it at all. I will try use this as a reference and extract some part of code that could be combine.

**Comment by Karambirov** [comment]
@5SMNOONMS5 I'll be waiting for your PR =)
