### ISSUE TITLE
Crash caused by delete operation of Realm

### ISSUE THREAD

**Issue by yaoxp** [Karambirov/GitHubSearch#57]
Open a 'About repository' interface.
1.  Click the 'Favorite' button,
2. then click the 'Unfavorite' button
3.  finally click the 'Favorite' button. 
The APP crashed.

Reason:
When you click the 'Unfavorite' button, the repository is delete from Realm
```
    func delete(_ object: Object) {
        // Deletes an object from the Realm. Once the object is deleted it is considered invalidated.
        write { $0.delete(object) }
    }
```

Now, the repository is considered invalidated and can no longer be accessed.

When finally click the 'Favorite' button, you access the deleted repository, so that APP crashed.
```
    @objc func favoriteButtonTapped() {
        if !viewModel.repository.isFavorite {  // crash
        ...
```

**Comment by Karambirov** [comment]
@yaoxp, thanks for your report! Can you fix it and create a PR? 🙂
